blueprint:
  name: Unavailable to Notification 
  description: >
    Sends a notification if an entity remains unavailable or unknown
    longer than the configured time.
  domain: automation

  input:
    target_entity:
      name: Entity to monitor
      selector:
        entity: {}

    timeout_hours:
      name: Hours before notification
      description: How long the entity must stay unavailable/unknown
      default: 2
      selector:
        number:
          min: 0.1
          max: 168
          step: 0.1
          mode: box

    notify_service:
      name: Notify service
      description: Example notify.mobile_app_phone
      default: notify.notify
      selector:
        text: {}

    message:
      name: Notification message
      default: "⚠️ The entity {{ states[input.target_entity].name }} has been offline for too long"
      selector:
        text: {}

mode: restart

trigger:
  - platform: state
    entity_id: !input target_entity
    to: "unavailable"
    for:
      hours: !input timeout_hours

  - platform: state
    entity_id: !input target_entity
    to: "unknown"
    for:
      hours: !input timeout_hours

action:
  - service: !input notify_service
    data:
      message: !input message