blueprint:
  name: Notify when entity is unavailable for too long
  description: >
    Sends a notification if an entity stays in unavailable or unknown
    state longer than the configured time. Uses an action picker so you
    can directly select a notify.mobile_app action or anything else.
  domain: automation

  input:

    target_entity:
      name: Entity to monitor
      selector:
        entity: {}

    timeout_hours:
      name: Hours before triggering
      default: 2
      selector:
        number:
          min: 0.1
          max: 168
          step: 0.1
          mode: box

    notify_action:
      name: Notification action
      description: >
        Pick any action (example: notify.mobile_app_yourphone).
        A default message template is already included.
      default:
        - service: notify.notify
          data:
            title: "Device offline"
            message: >
              ⚠️ {{ state_attr(target_entity, 'friendly_name') or target_entity }}
              has been unavailable for too long.
      selector:
        action: {}

mode: restart

trigger:

  - platform: state
    entity_id: !input target_entity
    to:
      - "unavailable"
      - "unknown"
    for:
      hours: !input timeout_hours

action:

  - variables:
      target_entity: !input target_entity

  - choose: []
    default: !input notify_action